### ISSUE TITLE
Can you include Assemblies folder in the github project?

### ISSUE THREAD

**Issue by Taranchuk** [CodeOptimist/assorted-alterations#1]
Not all users can use C# compilers, moreover, each time after a new version, we have to compile a new dll.

**Comment by CodeOptimist** [comment]
Sure. I always upload it to Steam but I suppose not everyone uses mods via Steam and also the code updates aren't going to be perfectly synchronized or identifiable for someone wanting to use a particular version. I'll do this from now on.
Done: https://github.com/CodeOptimist/assorted-alterations/commit/7b499df519f82c80b46060038cf6d9b8ea2e629e

**Comment by Taranchuk** [comment]
Ok, glad to hear that. I close the issue as solved.
