### ISSUE TITLE
Conflict with Rimworld Search Agency mod

### ISSUE THREAD

**Issue by Taranchuk** [CodeOptimist/assorted-alterations#2]
Mod adding a search box in storage tab - https://steamcommunity.com/sharedfiles/filedetails/?id=726479594
As soon as I type something in the search box, nothing is displayed and only visual glitches appear. Removing your mod from the modlist led to the disappearance of this problem and the above mod worked fine.

**Comment by CodeOptimist** [comment]
Thanks for submitting a report!! I actually use that mod, searches seem to work fine. A different mod conflicting with mine probably. If you can figure out which, I'll check it out!

**Comment by Taranchuk** [comment]
well, I start the game with just Hugslib, Rimworld Search Agency and Assorted Alterations and the error happens again. Here is the log: https://gist.github.com/HugsLibRecordKeeper/f0f886dc6328a8abf2ebd8722a27facb

I also noticed that there are errors at the start:
```
Config error in COAA_CannibalMealSurvivalPack: no label 
Config error in COAA_CannibalMealSimple: no label 
Config error in COAA_CannibalMealFine: no label 
Config error in COAA_CannibalMealLavish: no label 
Config error in COAA_CannibalPemmican: no label 
Config error in COAA_InsectMealSurvivalPack: no label 
Config error in COAA_InsectMealSimple: no label 
Config error in COAA_InsectMealFine: no label 
Config error in COAA_InsectMealLavish: no label 
Config error in COAA_InsectPemmican: no label 
Config error in COAA_CannibalMealSurvivalPack: no label 
Config error in COAA_CannibalMealSimple: no label 
Config error in COAA_CannibalMealFine: no label 
Config error in COAA_CannibalMealLavish: no label 
Config error in COAA_CannibalPemmican: no label 
Config error in COAA_InsectMealSurvivalPack: no label 
Config error in COAA_InsectMealSimple: no label 
Config error in COAA_InsectMealFine: no label 
Config error in COAA_InsectMealLavish: no label 
Config error in COAA_InsectPemmican: no label 
```
Do they somehow affect compatibility?

I have the latest version of the mod installed, from the master.

**Comment by Taranchuk** [comment]
I noticed that the error occurs when Russian language is set in the settings, when I change to English, this does not happen.

**Comment by CodeOptimist** [comment]
You were 100% correct. I completely misunderstood how missing language text was handled. Fixed in https://github.com/CodeOptimist/assorted-alterations/commit/f518d28586bd034fc5a25500d5aab56027158e0f as well as updated on Steam.

**Comment by Taranchuk** [comment]
The latest version fixed this error on my end.
